package team1.project.models;

public enum CardType {
    RANK_SQUIRE,
    RANK_KNIGHT,
    ADVENTURE_FOE,
    ADVENTURE_WEAPON,
    ADVENTURE_ALLY,
    ADVENTURE_AMOUR,
    ADVENTURE_TEST,
    STORY_QUEST,
    STORY_TOURNAMENT,
    STORY_EVENT
}
